// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_feyKVjfagK2mWriK_u1zvLpHvZT8yE4',
    appId: '1:1033360052874:web:99b260833000c48aea5373',
    messagingSenderId: '1033360052874',
    projectId: 'weather-alert-pk',
    authDomain: 'weather-alert-pk.firebaseapp.com',
    storageBucket: 'weather-alert-pk.firebasestorage.app',
    measurementId: 'G-D0F4QQ8NXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNgPwwHRNwMMGGdZhNKbg4yf6vhy0oekY',
    appId: '1:1033360052874:android:807548735dca0a42ea5373',
    messagingSenderId: '1033360052874',
    projectId: 'weather-alert-pk',
    storageBucket: 'weather-alert-pk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJddkvzlQIWS_2i1elUVk6kzo7FxobNmU',
    appId: '1:1033360052874:ios:810c1cf249e396c7ea5373',
    messagingSenderId: '1033360052874',
    projectId: 'weather-alert-pk',
    storageBucket: 'weather-alert-pk.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJddkvzlQIWS_2i1elUVk6kzo7FxobNmU',
    appId: '1:1033360052874:ios:810c1cf249e396c7ea5373',
    messagingSenderId: '1033360052874',
    projectId: 'weather-alert-pk',
    storageBucket: 'weather-alert-pk.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_feyKVjfagK2mWriK_u1zvLpHvZT8yE4',
    appId: '1:1033360052874:web:2dc80ebf3ecf348aea5373',
    messagingSenderId: '1033360052874',
    projectId: 'weather-alert-pk',
    authDomain: 'weather-alert-pk.firebaseapp.com',
    storageBucket: 'weather-alert-pk.firebasestorage.app',
    measurementId: 'G-YTR3HN0GXG',
  );
}
